### PR TITLE
Add "aforegoing"

### PR DESCRIPTION
**Pull request by grabbeh**

### CODE REVIEW

**Comment by kemitchell** [comment]
Michael, Thanks for the patch!

In addition, I found a few additional afore- words using the [words file](https://en.wikipedia.org/wiki/Words_%28Unix%29):

``` shellsession
cat /usr/share/dict/words | grep "^afore"
aforementioned
aforesaid
aforethought
```

Due credit for inspiration to come in two new commit messages!

**Comment by anseljh** [comment]
Ah, good old "[malice aforethought](https://en.wikipedia.org/wiki/Malice_aforethought)"... brings me back to criminal law in law school!

But, sorry lawyers, **s/malice aforethought/intent**.

:+1:

**Comment by kemitchell** [comment]
Of dead words speak no ill.

I'm sure there are litigation contexts where the old term of art is necessary. But it's archaic all the same.

**Comment by kemitchell** [comment]
This PR landed in version 1.0.6.

**Pull request closed without merging**
